twitter-to-kafka-service:
  twitter-keywords:
    - Java
    - Spring
    - Microservices
    - Elasticsearch
    - Kafka
  welcome-message: Hi friend!
  enable-mock-tweets: false
  mock-min-tweet-length: 5
  mock-max-tweet-length: 15
  mock-sleep-ms: 10000