twitter-to-kafka-service:
  twitter-keywords:
    - Java
    - Spring
    - Microservices
    - Elasticsearch
    - Kafka
  welcome-message: Hi friend!
  enable-mock-tweets: true
  mock-min-tweet-length: 5
  mock-max-tweet-length: 15
  mock-sleep-ms: 10000

retry-config:
  initial-interval-ms: 1000
  max-interval-ms: 10000
  multiplier: 2.0
  maxAttempts: 3
  sleep-time-ms: 2000

kafka-config:
  bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
  shcema-registry-url-key: schema.registy.url
  schema-registry-url: http://localhost:8081
  topic-name: twitter-topic
  topic-names-to-create:
    - twitter-topics
  num-of-partitions: 3
  replication-factor: 3

kafka-producer-config:
  key-serializer-class: org.apache.kafka.common.serialization.LongSerializer
  value-serializer-class: io.confluent.kafka.serializers.KafkaAvroSerializer
  compression-type: snappy
#  all: wait ack from all replicas; 1: wait only current broker's ack; 0: no ack
  acks: all
#  default value
  batch-size: 16384
#  tune for higher throughput
  batch-size-boost-factor: 100
#  add a delay on producer in case of light load
  linger-ms: 5
  request-timeout-ms: 60000
#  it will retry five times in case of error
  retry-count: 5

#  To increase throughput we can increase the batched data in request.
#  This can be done by increasing the batch size, adding a compression as batching is done after compression,
#  and increase the linger ms to add a delay on producer client to wait more and send more data at once.